config/routes.rb
Rails.application.routes.draw do
  root to: 'rooms#index'

  resources :rooms, only: [:new, :create, :show, :index]
  mount ActionCable.server => '/cable'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  after_create_commit {MessageBroadcastJob.perform_later self}
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :messages
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :rooms
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
  	@rooms = Room.all
  end

  def new
  	@room = Room.new
  end

  def create
  	@room = current_user.rooms.build(room_params)
    if @room.save
      flash[:success] = 'Room has been added!'
      redirect_to rooms_path
    else
      render 'new'
    end
  end

  def show
  	@room = Room.find(params[:id])
		@messages = @room.messages
	end

	private
		def room_params
			params.require(:room).permit(:topic)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleChat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class='message card'>
	<div class="card-header">
    	<%= message.user.email %> says:
  	</div>
  	<div class="card-block">
  		<p class="card-text"><%= message.content %></p>
  	</div>
</div>

app/views/rooms/_room.html.erb
<li class="list-group-item"><%= link_to room.topic, room_path(room) %></li>

app/views/rooms/index.html.erb
<h1>Choose a Chat Room</h1>
<ul class="list-group">
	<%= render @rooms %>
</ul>
<%= link_to 'Create new Chat Room', new_room_path, class: "btn btn-primary" %>

app/views/rooms/new.html.erb
<h1>Create a new Room</h1>

<%= form_for @room do |f| %>
  <div class="form-group">
    <%= f.label :topic %>
    <%= f.text_field :topic, class: 'form-control' %>
  </div>

  <%= f.submit "Add", class: 'btn btn-primary' %>
<% end %>

app/views/rooms/show.html.erb
<h1><%= @room.topic %></h1>
<div id='messages' data-room-id="<%= @room.id %>">
	<%= render @messages %>
</div>
<form>
	<label>Say something:</label><br>
	<input type="text" data-behavior="room_speaker" class="form-control">
</form>